// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can re-configure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALdDKeLHeXqnZfnZhpRTWGqjewhc9JrEY',
    appId: '1:907756483136:web:bb326f0fc31752cdfde5a5',
    messagingSenderId: '907756483136',
    projectId: 'lubrication-indicator',
    authDomain: 'lubrication-indicator.firebaseapp.com',
    databaseURL: 'https://lubrication-indicator-default-rtdb.firebaseio.com',
    storageBucket: 'lubrication-indicator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdDKeLHeXqnZfnZhpRTWGqjewhc9JrEY',
    appId: '1:907756483136:android:665ee54db3523adefde5a5',
    messagingSenderId: '907756483136',
    projectId: 'lubrication-indicator',
    databaseURL: 'https://lubrication-indicator-default-rtdb.firebaseio.com',
    storageBucket: 'lubrication-indicator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALdDKeLHeXqnZfnZhpRTWGqjewhc9JrEY',
    appId: '1:907756483136:ios:973e1be9d3f21210fde5a5',
    messagingSenderId: '907756483136',
    projectId: 'lubrication-indicator',
    databaseURL: 'https://lubrication-indicator-default-rtdb.firebaseio.com',
    storageBucket: 'lubrication-indicator.firebasestorage.app',
    iosBundleId: 'com.example.seva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALdDKeLHeXqnZfnZhpRTWGqjewhc9JrEY',
    appId: '1:907756483136:ios:973e1be9d3f21210fde5a5',
    messagingSenderId: '907756483136',
    projectId: 'lubrication-indicator',
    databaseURL: 'https://lubrication-indicator-default-rtdb.firebaseio.com',
    storageBucket: 'lubrication-indicator.firebasestorage.app',
    iosBundleId: 'com.example.seva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALdDKeLHeXqnZfnZhpRTWGqjewhc9JrEY',
    appId: '1:907756483136:web:b2d57e7a27d4512afde5a5',
    messagingSenderId: '907756483136',
    projectId: 'lubrication-indicator',
    authDomain: 'lubrication-indicator.firebaseapp.com',
    databaseURL: 'https://lubrication-indicator-default-rtdb.firebaseio.com',
    storageBucket: 'lubrication-indicator.firebasestorage.app',
  );
}
